### ISSUE TITLE
ENOENT: no such file or directory, stat './tsconfig.json'

### ISSUE THREAD

**Issue by Vallo** [alexgorbatchev/eslint-import-resolver-typescript#74] opened 2021-05-27 22:04 UTC
I have started a new react app and defined baseUrl as "./" on my tsconfig.json. Added `eslint-import-resolver-typescript` and empty settings on .eslintrc.js but still got `Unable to resolve path` error, despite imports worked as expected. Tried to specify tsconfig.json location on project property but got title error. All package.json, tsconfig.json and .eslintrc.js are on root folder, code is on /src. 

These are my current config files:

`.eslintrc.js`:

```javascript
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:import/recommended",
    "plugin:react/recommended",
    "airbnb",
    "plugin:prettier/recommended",
    "plugin:import/typescript",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: "module",
  },
  settings: {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"],
    },
    "import/resolver": {
      typescript: {},
    },
  },
  plugins: ["import", "react", "@typescript-eslint"],
  rules: {
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension": [
      2,
      { extensions: [".js", ".jsx", ".ts", ".tsx"] },
    ],
  },
};
}
```

```json
{
  "name": "react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "connected-react-router": "^6.9.1",
    "feather-icons": "^4.28.0",
    "history": "^5.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "redux": "^4.1.0",
    "typescript": "^4.3.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.25.0",
    "@typescript-eslint/parser": "^4.25.0",
    "eslint": "^7.27.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-import-resolver-typescript": "^2.4.0",
    "eslint-plugin-import": "^2.23.3",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.3.0"
  }
}
```
.tsconfig.json: 

```json
{
  "compilerOptions": {
    "noFallthroughCasesInSwitch": true,
    "target": "es5",
    "module": "esnext",
    "baseUrl": "./",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "noImplicitAny": false,
    "strict": true
  },
  "include": ["src"]
}
```

**Comment by JounQin** [comment] 2021-05-28 01:51
Please provide a minimal reproduction.

**Comment by Vallo** [comment] 2021-05-28 15:38
@JounQin  I created a minimal reproduction example. https://github.com/Vallo/eslint-import-resolver-typescript-reproduction

Not sure what causes it, but it only triggers if VS Code is not opened on project root folder. You can find reproduction steps on the readme. 

Thank you very much for your time

**Comment by JounQin** [comment] 2021-05-29 02:18
![image](https://user-images.githubusercontent.com/8336744/120055219-27649600-c067-11eb-8dcf-88dec07acedc.png)

I didn't get any error as you described.

**Comment by JounQin** [comment] 2021-05-29 02:36
If you mean `Unable to resolve path to module 'src/components/Example'`, I can reproduce it by `node ./project/node_modules/.bin/eslint ./project/src/App.tsx`, that is because the default `project` value is `process.cwd()`: https://github.com/alexgorbatchev/eslint-import-resolver-typescript/blob/master/src/index.ts#L214

It can be resolved by ESLint [`conext.getCwd()`](https://github.com/eslint/eslint/pull/12389), but `context` is not available in ESLint import resolver right now.

So the simple fix for now is setting `project` to be `__dirname` which represents `__dirname + '/tsconfig.json'` actually:

```diff
       "@typescript-eslint/parser": [".ts", ".tsx"],
     },
     "import/resolver": {
-      typescript: {},
+      typescript: {
+        project: __dirname,
+      },
     },
   },
   plugins: ["import", "react", "@typescript-eslint"],
```

**Closed by JounQin** 2021-05-29 02:36 UTC

**Comment by andre-lergier** [comment] 2022-02-24 09:18
I came up this issue because I had a quite similar error.
In my case I have a Monorepo using [Turborepo](https://turborepo.org/). In my Next.js app in the subfolder `apps/next-frontend` I had the problem, that ESLint in VSCode couldn't resolve the paths to my modules but while compiling everything worked well. If I put `"project": "./tsconfig.json"`, it didn't work in the IDE but while compiling. When I set `"project": "apps/next-frontend/tsconfig.json"` it worked in the IDE but not for compilation.

With the following options now everything is working without error - while compiling and in VSCode.

```json
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
        "typescript": {
          "project": "**/tsconfig.json"
        }
      }
   },
  "parser": "@typescript-eslint/parser",
  "plugins": ["import", "react", "@typescript-eslint"],
```

Maybe this helps someone else who comes across this issue. :)

**Comment by wlto** [comment] 2022-07-17 22:41
> I came up this issue because I had a quite similar error. In my case I have a Monorepo using [Turborepo](https://turborepo.org/). In my Next.js app in the subfolder `apps/next-frontend` I had the problem, that ESLint in VSCode couldn't resolve the paths to my modules but while compiling everything worked well. If I put `"project": "./tsconfig.json"`, it didn't work in the IDE but while compiling. When I set `"project": "apps/next-frontend/tsconfig.json"` it worked in the IDE but not for compilation.
> 
> With the following options now everything is working without error - while compiling and in VSCode.
> 
> ```json
>   "settings": {
>     "import/parsers": {
>       "@typescript-eslint/parser": [".ts", ".tsx"]
>     },
>     "import/resolver": {
>         "typescript": {
>           "project": "**/tsconfig.json"
>         }
>       }
>    },
>   "parser": "@typescript-eslint/parser",
>   "plugins": ["import", "react", "@typescript-eslint"],
> ```
> 
> Maybe this helps someone else who comes across this issue. :)

Thank you so much @andre-lergier ! Have been stuck with this for almost 2 hours. It's working on my end now. Cheers!

**Comment by JounQin** [comment] 2022-07-17 23:36
@wlto PR welcome!

**Comment by andyjessop** [comment] 2022-08-04 07:34
@JounQin `__dirname` won't work with json configs.

**Comment by JounQin** [comment] 2022-08-04 07:55
@andyjessop Then please raise a new issue with minimal but runnable reproduction.

**Comment by andyjessop** [comment] 2022-08-04 09:21
I agree, but there may be reasons teams cannot (or prefer not to) do that. It shouldn't be the case that a single plugin dictates which type of config you have to use.

**Comment by JounQin** [comment] 2022-08-04 09:37
> I agree, but there may be reasons teams cannot (or prefer not to) do that. It shouldn't be the case that a single plugin dictates which type of config you have to use.

Well, if you have good approach to improve this, feel free to create a PR instead.

**Comment by andyjessop** [comment] 2022-08-04 09:56
We did use this: `"project": "**/tsconfig.json"`, but in all honesty we reasoned that ESLint shouldn't be trying to resolve imports in TS files because TS already does that. Having ESLint do it too just adds an extra moving part that increases the complexity (and brittleness) of our configuration. So we set `"import/no-unresolved":"off"` for `.ts` files.

**Comment by JounQin** [comment] 2022-08-04 10:01
> We did use this: `"project": "**/tsconfig.json"`, but in all honesty we reasoned that ESLint shouldn't be trying to resolve imports in TS files because TS already does that. Having ESLint do it too just adds an extra moving part that increases the complexity (and brittleness) of our configuration. So we set `"import/no-unresolved":"off"` for `.ts` files.

It's OK, and this resolver works without `typescript` dep for performance, of course.
